### ISSUE TITLE
Online API

### ISSUE THREAD

**Issue by larjohn** [openbudgets/outlier-dm-ionic2#2]
Is there a working online API so that I can see what this application does without hassling too much with the deployment stuff?

**Comment by larjohn** [comment]
Hi @pierorex,
I am trying to integrate this to indigo but I can't understand how to have the same results from DAM. For instance, the following is a response that outlier-dm-ionic2 gets from its backend:
`[{"x":1,"color":"Reserved","y":169.0,"size":3130.3120085113},{"x":1,"color":"Approved","y":168.5,"size":3121.9754918442},{"x":1,"color":"Executed","y":13562748.1600000001,"size":9.7260750421},{"x":1,"color":"Draft","y":400000.0,"size":3.6073342338},{"x":1,"color":"Revised","y":400000.0,"size":3.6073342338},{"x":1,"color":"Draft","y":4300000.0,"size":2.4118930751},{"x":1,"color":"Revised","y":4300000.0,"size":2.4118930751},{"x":1,"color":"Draft","y":4000.0,"size":2.1092110665},{"x":1,"color":"Revised","y":4000.0,"size":2.1092110665},{"x":1,"color":"Draft","y":5000.0,"size":1.924249741},{"x":1,"color":"Revised","y":5000.0,"size":1.924249741},{"x":1,"color":"Executed","y":1122409.71,"size":1.902340548},{"x":1,"color":"Reserved","y":4500.0,"size":1.8243882052},{"x":1,"color":"Draft","y":2825000.0,"size":1.7713020678},{"x":1,"color":"Draft","y":220000.0,"size":1.6274931223},{"x":1,"color":"Revised","y":220000.0,"size":1.6274931223},{"x":1,"color":"Approved","y":217973.37,"size":1.6128272425},{"x":1,"color":"Executed","y":217973.37,"size":1.6128272425},{"x":1,"color":"Executed","y":150000.0,"size":1.5155528965},{"x":1,"color":"Executed","y":900000.0,"size":1.5150850826},{"x":1,"color":"Reserved","y":1226389.0,"size":1.4984703236},{"x":1,"color":"Executed","y":80000.0,"size":1.4633254886},{"x":1,"color":"Reserved","y":11600.0,"size":1.4235817137},{"x":1,"color":"Revised","y":2450000.0,"size":1.3874614294},{"x":1,"color":"Revised","y":2440000.0,"size":1.377225679}]
`

I would like to get a similar result from DAM in order to reuse your visualization. Is there a request that can get this results from DAM?

**Comment by pierorex** [comment]
Hi @larjohn,
No, DAM doesn't provide the output in that format, you can read here how I parse DAM responses to build it that way: https://github.com/openbudgets/outlier_dm/blob/master/webapp/app.py
